#spring:
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/spring-data-jpa
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 5000
#      pool-name: bharath
#      maximum-pool-size: 10


server:
  port: 9090
 
spring:
  h2:
    console:
      enabled: true
      path: /h2-console